name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_and_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Ajoutez vos tâches de test et de CI ici
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Spécifiez la version de Python que vous utilisez

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Installer pytest
        working-directory: app/  # Spécifiez le chemin vers votre code Python

      - name: Run tests with pytest
        run: |
          pytest
        #working-directory: app/

    #######

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --exclude=test_my_module.py
        working-directory: app/

      - name: Install radon
        run: pip install radon

      - name: Analyze Cyclomatic Complexity
        run: radon cc -s -a -e "venv/*" .

      - name: Install cpplint
        run: pip install cpplint

      - name: Check Code Duplication
        run: cpplint --recursive .





    #######      

  cd:
    runs-on: ubuntu-latest
    needs: test_and_ci
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Ajoutez vos tâches de déploiement (CD) ici
